name: Deploy Node Applicaiton

on:
    push:
        branches:
            - mern-ec2-docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run:  docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -  t tlotlang/back-end .
      - name: Publish Image to docker hub
        run: docker push tlotlang/back-end:latest
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull tlotlang/back-end:latest
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name back-end-container -e MONGO_PASSWORD='${{secrets.MONGO_PASSWORD}}' tlotlang/back-end
